repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=50000']  # Block files > 50MB

  - repo: https://github.com/google/yapf
    rev: v0.40.1
    hooks:
      - id: yapf
        name: yapf
        description: "Auto-formats python code"
        entry: yapf
        language: python
        types: [python]
        args: ['-i']
